package com.example.demo.enums;

public enum TipoNotificacao {
    CHECK_IN,
    NOVO_DESAFIO,
    NOVO_MEMBRO,
    NOVO_COMENTARIO,
    ALERTA_TEMPO,
    DESAFIO_ENCERRADO,
    PREMIO_DESAFIO, DESAFIO_CANCELADO, CONVITE_GRUPO, CONVITE_DESAFIO, NOVO_MEMBRO_DESAFIO
}
